version: '3.1'
services:
    web:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - .:/var/www/html/
        networks:
            - default
volumes:
    persistent: